name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: docker-python-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: List Files
        run: |
          pwd
          ls -la /

      - name: Check out
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo
        run: |
          echo ${{ env.REGISTRY }}
          echo ${{ env.IMAGE_NAME }}
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          echo $IMAGE_TAG

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  run:
    needs: build
    runs-on: ubuntu-latest
    services:
      test-container:
        image: ghcr.io/hanley-dev/docker-python-test:latest
        ports:
          - 8080:8080
    steps:
      - name: List Files
        run: |
          pwd
          ls -la
          ls -la /
      - name: Call endpoint
        run: |
          curl -v http://127.0.0.1:8080/
