name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: docker-python-test

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: List Initial Containers
        run: |
          docker images
      - name: Build Container
        env:
          IMAGE_TAG: docker-python-test
        run: |
          docker build -t $IMAGE_TAG .
      - name: List Containers after Build
        run: |
          docker images
      - name: Run Containers
        run: |
          docker run --rm $IMAGE_TAG ls -l
      - name: Call endpoint
        run: |
          curl http://localhost:8080/
