name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: docker-python-test

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: List Initial Containers
        run: |
          docker images
      - name: Build Container
        env:
          IMAGE_TAG: docker-python-test
        run: |
          docker build -t $IMAGE_TAG .
      - name: List Containers after Build
        run: |
          docker images
      - name: Run Containers
        run: |
          docker run $IMAGE_TAG ls -l
#      - name: Call endpoint
#        run: |
#          docker run -d -p 8080:8080 $IMAGE_TAG
#          curl -v http://127.0.0.1:8080/

#  run:
#    if: "!contains(github.event.head_commit.message, 'skip ci')"
#    needs: build
#    runs-on: ubuntu-latest
#    container:
#      image: docker-python-test
#      ports:
#        - 8080:8080
#    steps:
#      - name: Call endpoint
#        run: |
#          curl -v http://127.0.0.1:8080/
